"""Initial migration.

Revision ID: 9f92bab260e5
Revises: ac387d08b73c
Create Date: 2023-03-18 21:48:08.474962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f92bab260e5'
down_revision = 'ac387d08b73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address1',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
