"""Initial migration1.

Revision ID: ac387d08b73c
Revises: f9c7e1042422
Create Date: 2023-03-13 20:42:48.129470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac387d08b73c'
down_revision = 'f9c7e1042422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
