"""Initial migration.

Revision ID: f9c7e1042422
Revises: 2ded7d841fa6
Create Date: 2023-03-13 11:04:46.937677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c7e1042422'
down_revision = '2ded7d841fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sku')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
